services:
  - type: static
    name: quize-game-front
    env: static
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    publishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    routing:
      - source: /[^.]*
        destination: /index.html
        type: rewrite